import { NextResponse } from "next/server";
import Digest from "../../../../../../models/digest.mjs";
import { getCurrentUser } from "../../../../../../utils/auth";
import { enqueueBuildDigest } from "../../../utils";

export async function POST(req, { params }) {
    params = await params;
    const user = await getCurrentUser();
    const { id } = params;

    let digest = await Digest.findOne({
        owner: user._id,
    });

    if (!digest) {
        return NextResponse.json(
            { message: "Digest not found" },
            { status: 404 },
        );
    }

    const block = digest.blocks.find((b) => b._id.toString() === id.toString());

    if (!block) {
        return NextResponse.json(
            { message: "Block not found" },
            { status: 404 },
        );
    }

    // Automation-linked blocks display the linked automation's latest run.
    // They are not built by the digest worker, so regenerating is a no-op.
    if (block.automationId) {
        return NextResponse.json(
            {
                message:
                    "Automation-linked blocks are not regenerated by the digest system.",
            },
            { status: 400 },
        );
    }

    const { taskId } = await enqueueBuildDigest(user._id, id);
    block.taskId = taskId;

    digest = await Digest.updateOne(
        {
            owner: user._id,
        },
        {
            $set: {
                blocks: digest.blocks,
            },
        },
        {
            new: true,
        },
    );

    return NextResponse.json(digest);
}
