// Standard variable builder for all models — maps user settings to media_generate params
export function buildMediaVariables(
    model,
    prompt,
    settings,
    inputImages,
    inputImageRoles,
    inputVideos,
    inputAudioUrl,
    inputAudios,
) {
    return {
        model,
        text: prompt,
        async: true,
        inputImages: inputImages || [],
        inputImageRoles: inputImageRoles || [],
        inputVideos: inputVideos || [],
        inputAudio: inputAudios || (inputAudioUrl ? [inputAudioUrl] : []),
        fps: settings.fps,
        generationMode: settings.generationMode,
        watermark: settings.watermark,
        matchInputImage: settings.matchInputImage,
        enablePromptExpansion: settings.enablePromptExpansion,
        layerDecomposition: settings.layerDecomposition,
        styleId: settings.styleId,
        styleMatch: settings.styleMatch,
        sourceUrl: settings.sourceUrl,
        sourceLanguage: settings.sourceLanguage,
        targetLanguage: settings.targetLanguage,
        cloningStrength: settings.cloningStrength,
        background: settings.background,
        outputCompression: settings.outputCompression,
        promptUpsampler: settings.promptUpsampler,
        draft: settings.draft,
        autoAspectRatio: settings.autoAspectRatio,
        webGrounding: settings.webGrounding,
        aspectRatio: settings.aspectRatio,
        duration: settings.duration,
        outputFormat: settings.outputFormat || settings.output_format,
        outputQuality: settings.outputQuality ?? settings.output_quality,
        quality: settings.quality, // model render quality preset (low|medium|high|auto)
        negativePrompt: settings.negativePrompt,
        numberResults: settings.numberResults,
        seed: settings.seed,
        optimizePrompt: settings.optimizePrompt,
        generateAudio: settings.generateAudio,
        forceInstrumental:
            settings.forceInstrumental ?? settings.force_instrumental,
        processingType: settings.processingType || settings.processing_type,
        scene: settings.scene,
        targetResolution:
            settings.targetResolution || settings.target_resolution,
        targetFps: settings.targetFps || settings.target_fps,
        enhanceModel: settings.enhanceModel || settings.enhance_model,
        upscaleFactor: settings.upscaleFactor || settings.upscale_factor,
        subjectDetection:
            settings.subjectDetection || settings.subject_detection,
        faceEnhancement: settings.faceEnhancement ?? settings.face_enhancement,
        faceEnhancementCreativity:
            settings.faceEnhancementCreativity ??
            settings.face_enhancement_creativity,
        faceEnhancementStrength:
            settings.faceEnhancementStrength ??
            settings.face_enhancement_strength,
        cutFirstSecond: settings.cutFirstSecond ?? settings.cut_first_second,
        noOp: settings.noOp ?? settings.no_op,
        resolution: settings.resolution,
        cameraFixed: settings.cameraFixed,
        imageSize: settings.imageSize || settings.image_size,
        width: settings.width,
        height: settings.height,
        size: settings.size,
        lyrics: settings.lyrics,
        isInstrumental: settings.isInstrumental ?? settings.is_instrumental,
        lyricsOptimizer: settings.lyricsOptimizer ?? settings.lyrics_optimizer,
        audioUrl: settings.audioUrl || settings.audio_url,
        inputAudioUrl:
            inputAudioUrl || settings.inputAudioUrl || settings.input_audio_url,
        audioFormat: settings.audioFormat || settings.audio_format,
        sampleRate: settings.sampleRate || settings.sample_rate,
        bitrate: settings.bitrate,
        voiceName: settings.voiceName,
        speaker1Name: settings.speaker1Name,
        speaker1VoiceName: settings.speaker1VoiceName,
        speaker2Name: settings.speaker2Name,
        speaker2VoiceName: settings.speaker2VoiceName,
        mode: settings.mode,
        language: settings.language,
        speaker: settings.speaker,
        referenceText: settings.referenceText || settings.reference_text,
        styleInstruction:
            settings.styleInstruction || settings.style_instruction,
        voiceDescription:
            settings.voiceDescription || settings.voice_description,
        voice: settings.voice,
        voiceScript: settings.voiceScript || settings.voice_script,
        voiceLanguage: settings.voiceLanguage || settings.voice_language,
        voicePrompt: settings.voicePrompt || settings.voice_prompt,
        videoPrompt: settings.videoPrompt || settings.video_prompt,
        strengthNegativePrompt:
            settings.strengthNegativePrompt ??
            settings.strength_negative_prompt,
        disableSafetyFilter:
            settings.disableSafetyFilter ?? settings.disable_safety_filter,
        disablePromptUpsampling:
            settings.disablePromptUpsampling ??
            settings.disable_prompt_upsampling,
        stability: settings.stability,
        similarityBoost: settings.similarityBoost ?? settings.similarity_boost,
        style: settings.style,
        speed: settings.speed,
        previousText: settings.previousText || settings.previous_text,
        nextText: settings.nextText || settings.next_text,
        languageCode: settings.languageCode || settings.language_code,
        voiceId: settings.voiceId || settings.voice_id,
        customVoiceId: settings.customVoiceId || settings.custom_voice_id,
        volume: settings.volume,
        pitch: settings.pitch,
        emotion: settings.emotion,
        channel: settings.channel,
        languageBoost: settings.languageBoost || settings.language_boost,
        subtitleEnable: settings.subtitleEnable ?? settings.subtitle_enable,
        englishNormalization:
            settings.englishNormalization ?? settings.english_normalization,
    };
}

// Accepted setting names, including the aliases supported by the worker.
export const MEDIA_SETTING_KEYS = [
    "fps",
    "generationMode",
    "watermark",
    "matchInputImage",
    "enablePromptExpansion",
    "layerDecomposition",
    "styleId",
    "styleMatch",
    "sourceUrl",
    "sourceLanguage",
    "targetLanguage",
    "cloningStrength",
    "background",
    "outputCompression",
    "promptUpsampler",
    "draft",
    "autoAspectRatio",
    "webGrounding",
    "aspectRatio",
    "duration",
    "outputFormat",
    "output_format",
    "outputQuality",
    "output_quality",
    "quality",
    "negativePrompt",
    "numberResults",
    "seed",
    "optimizePrompt",
    "generateAudio",
    "forceInstrumental",
    "force_instrumental",
    "processingType",
    "processing_type",
    "scene",
    "targetResolution",
    "target_resolution",
    "targetFps",
    "target_fps",
    "enhanceModel",
    "enhance_model",
    "upscaleFactor",
    "upscale_factor",
    "subjectDetection",
    "subject_detection",
    "faceEnhancement",
    "face_enhancement",
    "faceEnhancementCreativity",
    "face_enhancement_creativity",
    "faceEnhancementStrength",
    "face_enhancement_strength",
    "cutFirstSecond",
    "cut_first_second",
    "noOp",
    "no_op",
    "resolution",
    "cameraFixed",
    "imageSize",
    "image_size",
    "width",
    "height",
    "size",
    "lyrics",
    "isInstrumental",
    "is_instrumental",
    "lyricsOptimizer",
    "lyrics_optimizer",
    "audioUrl",
    "audio_url",
    "inputAudioUrl",
    "input_audio_url",
    "audioFormat",
    "audio_format",
    "sampleRate",
    "sample_rate",
    "bitrate",
    "voiceName",
    "speaker1Name",
    "speaker1VoiceName",
    "speaker2Name",
    "speaker2VoiceName",
    "mode",
    "language",
    "speaker",
    "referenceText",
    "reference_text",
    "styleInstruction",
    "style_instruction",
    "voiceDescription",
    "voice_description",
    "voice",
    "voiceScript",
    "voice_script",
    "voiceLanguage",
    "voice_language",
    "voicePrompt",
    "voice_prompt",
    "videoPrompt",
    "video_prompt",
    "strengthNegativePrompt",
    "strength_negative_prompt",
    "disableSafetyFilter",
    "disable_safety_filter",
    "disablePromptUpsampling",
    "disable_prompt_upsampling",
    "stability",
    "similarityBoost",
    "similarity_boost",
    "style",
    "speed",
    "previousText",
    "previous_text",
    "nextText",
    "next_text",
    "languageCode",
    "language_code",
    "voiceId",
    "voice_id",
    "customVoiceId",
    "custom_voice_id",
    "volume",
    "pitch",
    "emotion",
    "channel",
    "languageBoost",
    "language_boost",
    "subtitleEnable",
    "subtitle_enable",
    "englishNormalization",
    "english_normalization",
];
