import { NextResponse } from "next/server";

export async function POST(request, { params }) {
    const { messages } = await request.json();

    // Randomly choose between HTML and text response
    const useHtml = Math.random() > 0.5;

    let response;
    if (useHtml) {
        response = {
            message:
                '`<div class="bg-blue-100 p-4 rounded-lg"><h2 class="text-xl font-bold mb-2">Sample Component</h2><p class="text-gray-700">This is a sample HTML component generated by the AI.</p><button class="mt-2 px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600">Click me</button></div>`',
        };
    } else {
        response = {
            message:
                "I understand you want to create a UI. Let me help you with that. What specific elements would you like to include?",
        };
    }

    return NextResponse.json(response);
}
