const NEXT_PUBLIC_MEDIA_API_URL = process.env.NEXT_PUBLIC_MEDIA_API_URL;

const NEXT_PUBLIC_API_SUBSCRIPTION_KEY =
    process.env.NEXT_PUBLIC_API_SUBSCRIPTION_KEY || "";

export { NEXT_PUBLIC_MEDIA_API_URL, NEXT_PUBLIC_API_SUBSCRIPTION_KEY };
