# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - aj-labeeb

on:
    push:
        branches:
            - main
            - dev
            - ARC-2252
    workflow_dispatch:

env:
    image_tag: "${{ github.sha }}-${{ github.run_id }}"
    app_name: "aj-labeeb"
    slot_name: ${{ github.ref == 'refs/heads/main' && 'blue' || 'dev' }}

jobs:
    build:
        environment: ${{ github.ref == 'refs/heads/main' && 'blue' || 'dev' }}
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Log in to container registry
              uses: docker/login-action@v2
              with:
                  registry: https://archipelagoairegistry.azurecr.io/
                  username: ${{ secrets.AZURE_CONTAINERREGISTRY_USERNAME }}
                  password: ${{ secrets.AZURE_CONTAINERREGISTRY_PASSWORD }}

            - name: Build and push container image to registry
              uses: docker/build-push-action@v3
              with:
                  context: .
                  push: true
                  tags: archipelagoairegistry.azurecr.io/labeeb:${{env.image_tag}}
                  file: ./Dockerfile
                  build-args: |
                      CORTEX_GRAPHQL_API_URL=${{secrets.CORTEX_GRAPHQL_API_URL}}
                      CORTEX_MEDIA_API_URL=${{secrets.CORTEX_MEDIA_API_URL}}
                      NEXT_PUBLIC_AMPLITUDE_API_KEY=${{secrets.NEXT_PUBLIC_AMPLITUDE_API_KEY}}
                      NEXT_PUBLIC_ATLASSIAN_CLIENT_ID=${{secrets.NEXT_PUBLIC_ATLASSIAN_CLIENT_ID}}
                      NEXT_PUBLIC_BASE_PATH=${{vars.NEXT_PUBLIC_BASE_PATH}}
                      NEXT_PUBLIC_NEXTJS_SERVER_URL=${{vars.NEXT_PUBLIC_NEXTJS_SERVER_URL}}

    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: ${{ github.ref == 'refs/heads/main' && 'blue' || 'dev' }}
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

        steps:
            - name: "Deploy to ${{env.app_name }}, '${{env.slot_name}}' slot"
              id: deploy-to-webapp
              uses: azure/webapps-deploy@v2
              with:
                  app-name: ${{ env.app_name }}
                  slot-name: ${{ env.slot_name }}
                  publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
                  images: archipelagoairegistry.azurecr.io/labeeb:${{env.image_tag}}
